#%RAML 1.0
title: OYO Hotels REST API

types:
  Hotel: !include dataTypes/HotelDataType.raml


/hotels:
  get:
    displayName: Get Hotels By City
    description: Get Hotels By City Description
    queryParameters:
      city:
        required: true
        type: string
        enum:
          - Bangalore
          - Hyderabad
          - Mumbai
          - Delhi
        example: Bangalore
      priceUnder:
        type: integer
        required: false
        example: 50000
        default: 25000
      startDate:
        type: string
        pattern: ^(([0-9])|([0-2][0-9])|([3][0-1])) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{4}$
        required: false
        example: 15 Feb 2022
      endDate:  
        type: string
        pattern: ^(([0-9])|([0-2][0-9])|([3][0-1])) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{4}$
        required: false
        example: 15 Feb 2022
    responses:
      200:
        body:
          application/json:
            type: Hotel[]
            example: !include examples/HotelsExample.raml
  post:
    displayName: Add Hotel
    description: Add Hotel Description
    body:
      application/json:
        example: !include examples/HotelExample.raml
        type:  Hotel
    responses:
      201:
        body:
          application/json:
            example:
              message: Hotel has been added

  /{hotelId}:
    uriParameters:
      hotelId:
        type: integer
        minimum: 1
        maximum: 5000
    get:
      displayName: Get Hotel By Hotel ID
      description: Get Hotel By Hotel ID Description
      responses:
        200:
          body:
            application/json:
              example: !include examples/HotelExample.raml
              type: Hotel   
    put:
      displayName: Update Hotel By Hotel ID
      description: Update Hotel By Hotel ID Description
      body:
        application/json:
          example: !include examples/HotelExample.raml
          type:  Hotel
      responses:
        201:
          body:
            application/json:
              example:
                message: Hotel has been updated
    delete:
      displayName: Delete Hotel By Hotel ID
      description: Delete Hotel By Hotel ID Description
      responses:
        200:
          body:
            application/json:
              example:
                message: Hotel has been deleted
